apiVersion: v1
kind: Pod
metadata:
  name: traffic-generator
  namespace: dapr-services
spec:
  containers:
  - name: curl
    image: curlimages/curl:latest
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
  restartPolicy: Never
